### ISSUE TITLE
Days to next birthday are horrendously wrong

### ISSUE THREAD

**Issue by namtrah** [Raboro/Obsidian-Birthday-Tracker-Plugin#10]
I cannot see any debug info to tell me why this is, but I have a file as described which is giving me 2000 days until the next birthday, for example. I attach a picture to see if this helps. FWIW, I have Calendarium Plugin installed with a default of a otherworldly calendar. I do not see in the code of this plugin that it matters, but I wanted to have said it.

My Markdown code is as follows:

```
## Birthdays

name=Eric; birthday=1984-01-09
name=Franz;birthday=1984-11-28
name=Imke;birthday=2000-03-03
name=Kai;birthday=1984-06-23
name=Matthias;birthday=1997-03-06
name=Philipp;birthday=2000-05-07
name=Trick;birthday=1969-12-05
```

**Comment by namtrah** [comment]
I am closing, as the error was more or less a user error. No space between the semicolon and `birthday`. Still would be great if this was more resiliant.

**Comment by Raboro** [comment]
made more spaces possible: [new release](https://github.com/Raboro/Obsidian-Birthday-Tracker-Plugin/releases/tag/1.1.1)
