### ISSUE TITLE
Month of May is mispelled

### ISSUE THREAD

**Issue by deonjo** [Raboro/Obsidian-Birthday-Tracker-Plugin#12]
Hope this is an easy fix! Thanks for making this awesome plugin!

<img width="319" alt="Screenshot 2024-04-02 at 2 44 29 PM" src="https://github.com/Raboro/Obsidian-Birthday-Tracker-Plugin/assets/461874/013b19ac-9758-462e-9ecd-83ad7155a034">

**Comment by Raboro** [comment]
thanks, fixed in [1.1.2](https://github.com/Raboro/Obsidian-Birthday-Tracker-Plugin/releases/tag/1.1.2)
