### ISSUE TITLE
Year View

### ISSUE THREAD

**Issue by sirnails** [Raboro/Obsidian-Birthday-Tracker-Plugin#6]
How do you open year view?
is it different to open year view on mobile?

**Comment by sirnails** [comment]
I found a way with the built in command palette by typing "Birthday" then choosing year from the drop down.
There doesnt seem to be a button to open the year view? 
could this be a feature request to add a button on the birthday tracker at the top with year view?

**Comment by Raboro** [comment]
Thanks for your suggestion. I could also create a Ribbon icon for the year view.

**Comment by Raboro** [comment]
included in [1.1.0](https://github.com/Raboro/Obsidian-Birthday-Tracker-Plugin/releases/tag/1.1.0)

**Comment by sirnails** [comment]
Ace, thank you!
